export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  WORKFLOW_INVALID_TRANSITION: 'WORKFLOW_INVALID_TRANSITION',
  PROJECT_RECORD_LOCKED: 'PROJECT_RECORD_LOCKED',
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  FILE_UPLOAD_INVALID_TYPE: 'FILE_UPLOAD_INVALID_TYPE',
  FILE_UPLOAD_TOO_LARGE: 'FILE_UPLOAD_TOO_LARGE',
  RESULT_ACCESS_DENIED: 'RESULT_ACCESS_DENIED',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
